"""Consolidated architecture

Revision ID: 5c5c0e0ef686
Revises: 
Create Date: 2026-08-17 14:23:49.734900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5c0e0ef686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_login_attempts_attempt_id'), 'login_attempts', ['attempt_id'], unique=False)
    op.create_table('properties',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_no', sa.String(length=10), nullable=False),
    sa.Column('complex_name', sa.String(length=255), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('suburb', sa.String(length=255), nullable=True),
    sa.Column('size_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('unit_no')
    )
    op.create_index(op.f('ix_properties_unit_id'), 'properties', ['unit_id'], unique=False)
    op.create_table('service_providers',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_service_providers_provider_id'), 'service_providers', ['provider_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phoneno', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('unit_no', sa.String(length=10), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('hoa_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('ai_analytics',
    sa.Column('analytics_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('predicted_market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rental_yield_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growth_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ten_year_roi', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calculated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('input_features_used', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_index(op.f('ix_ai_analytics_analytics_id'), 'ai_analytics', ['analytics_id'], unique=False)
    op.create_table('announcements',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_index(op.f('ix_announcements_announcement_id'), 'announcements', ['announcement_id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaints_complaint_id'), 'complaints', ['complaint_id'], unique=False)
    op.create_table('listings',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listings_listing_id'), 'listings', ['listing_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['properties.unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('maintenance_work_orders',
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('job_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resident_rating', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('estimated_completion_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('actual_completion_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    op.create_index(op.f('ix_maintenance_work_orders_work_order_id'), 'maintenance_work_orders', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_work_orders_work_order_id'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_listings_listing_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_complaints_complaint_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_announcements_announcement_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_ai_analytics_analytics_id'), table_name='ai_analytics')
    op.drop_table('ai_analytics')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_providers_provider_id'), table_name='service_providers')
    op.drop_table('service_providers')
    op.drop_index(op.f('ix_properties_unit_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_login_attempts_attempt_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
