/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoaRouteImport } from './routes/hoa'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as ResidentRouteImport } from './routes/resident'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoaRoute = HoaRouteImport.update({
  id: '/hoa',
  path: '/hoa',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hoa': typeof HoaRoute
  '/investor': typeof InvestorRoute
  '/resident': typeof ResidentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hoa': typeof HoaRoute
  '/investor': typeof InvestorRoute
  '/resident': typeof ResidentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hoa': typeof HoaRoute
  '/investor': typeof InvestorRoute
  '/resident': typeof ResidentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hoa' | '/investor' | '/resident'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hoa' | '/investor' | '/resident'
  id: '__root__' | '/' | '/hoa' | '/investor' | '/resident'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HoaRoute: typeof HoaRoute
  InvestorRoute: typeof InvestorRoute
  ResidentRoute: typeof ResidentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoa': {
      id: '/hoa'
      path: '/hoa'
      fullPath: '/hoa'
      preLoaderRoute: typeof HoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HoaRoute: HoaRoute,
  InvestorRoute: InvestorRoute,
  ResidentRoute: ResidentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
